# Generated by Django 6.0.6 on 2026-06-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utilisateurs", "0002_administrateur_agriculteur_agronome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom de la culture"),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Superficie (ha)"
                    ),
                ),
                (
                    "date_plantation",
                    models.DateField(verbose_name="Date de plantation"),
                ),
                (
                    "localisation",
                    models.CharField(max_length=255, verbose_name="Localisation"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "agriculteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cultures",
                        to="utilisateurs.agriculteur",
                        verbose_name="Agriculteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
                "ordering": ["-date_creation"],
            },
        ),
    ]
