# Generated by Django 6.0.6 on 2026-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultures", "0001_initial"),
        ("utilisateurs", "0002_administrateur_agriculteur_agronome_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="culture",
            options={
                "ordering": ["-date_modification"],
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
            },
        ),
        migrations.AlterUniqueTogether(
            name="culture",
            unique_together={("agriculteur", "nom")},
        ),
        migrations.AddIndex(
            model_name="culture",
            index=models.Index(fields=["nom"], name="cultures_cu_nom_ecf61d_idx"),
        ),
        migrations.AddIndex(
            model_name="culture",
            index=models.Index(
                fields=["date_plantation"], name="cultures_cu_date_pl_a10f37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="culture",
            index=models.Index(
                fields=["localisation"], name="cultures_cu_localis_8907c6_idx"
            ),
        ),
    ]
