# Generated by Django 5.2.7 on 2026-06-27 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cultures",
            "0002_alter_culture_options_alter_culture_unique_together_and_more",
        ),
        ("utilisateurs", "0002_administrateur_agriculteur_agronome_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="culture",
            options={
                "ordering": ["-date_semis"],
                "verbose_name": "Culture",
                "verbose_name_plural": "Cultures",
            },
        ),
        migrations.RemoveIndex(
            model_name="culture",
            name="cultures_cu_date_pl_a10f37_idx",
        ),
        migrations.RemoveField(
            model_name="culture",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="culture",
            name="date_modification",
        ),
        migrations.RemoveField(
            model_name="culture",
            name="date_plantation",
        ),
        migrations.RemoveField(
            model_name="culture",
            name="description",
        ),
        migrations.AddField(
            model_name="culture",
            name="date_semis",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de semis"
            ),
        ),
        migrations.AddField(
            model_name="culture",
            name="statut",
            field=models.CharField(
                default="En cours", max_length=50, verbose_name="Statut"
            ),
        ),
        migrations.AddIndex(
            model_name="culture",
            index=models.Index(
                fields=["date_semis"], name="cultures_cu_date_se_5cff7e_idx"
            ),
        ),
    ]
