# Generated by Django 6.0.6 on 2026-06-27 15:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cultures", "0003_alter_culture_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommandation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dateRecommandation",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de recommandation",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=100, verbose_name="Type de recommandation"
                    ),
                ),
                (
                    "contenu",
                    models.TextField(verbose_name="Contenu de la recommandation"),
                ),
                (
                    "culture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommandations",
                        to="cultures.culture",
                        verbose_name="Culture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation",
                "verbose_name_plural": "Recommandations",
                "ordering": ["-dateRecommandation", "-id"],
                "indexes": [
                    models.Index(
                        fields=["dateRecommandation"],
                        name="recommandat_dateRec_e5b7cc_idx",
                    ),
                    models.Index(
                        fields=["culture"], name="recommandat_culture_110c67_idx"
                    ),
                ],
                "unique_together": {("culture", "dateRecommandation")},
            },
        ),
    ]
