# Generated by Django 6.0.6 on 2026-06-26 06:19

import django.db.models.deletion
import utilisateurs.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrateur",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrateur",
                "verbose_name_plural": "Administrateurs",
            },
            bases=("utilisateurs.utilisateur",),
            managers=[
                ("objects", utilisateurs.managers.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name="Agriculteur",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agriculteur",
                "verbose_name_plural": "Agriculteurs",
            },
            bases=("utilisateurs.utilisateur",),
            managers=[
                ("objects", utilisateurs.managers.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name="Agronome",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agronome",
                "verbose_name_plural": "Agronomes",
            },
            bases=("utilisateurs.utilisateur",),
            managers=[
                ("objects", utilisateurs.managers.UtilisateurManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="utilisateur",
            managers=[
                ("objects", utilisateurs.managers.UtilisateurManager()),
            ],
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Adresse e-mail"
            ),
        ),
    ]
