# Generated by Django 5.2.7 on 2026-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observation",
            options={"ordering": ["-date_observation"]},
        ),
        migrations.RemoveField(
            model_name="observation",
            name="commentaire",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="date_modification",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="observateur",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="type",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="valeur",
        ),
        migrations.AddField(
            model_name="observation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
